Feat default provider
Tutellus/hw-poc-app pull request #30
Opened 2023-09-26 06:54 UTC by davecarter

make `mock provider` default

2023-09-26 07:10 UTC, danivm approved these changes

2023-09-28 08:49 UTC, sokardys requested changes

2023-09-28 08:49 UTC, sokardys commented on components/templates/Login.jsx
> +  const [storedProvider, setStoredProvider] = useState("mock")
Esto no invalida el useEfect que pone el mock en las L34-L36?

2023-09-28 08:49 UTC, sokardys commented on state/human.context.js
> +    let provider
Quizá inicializar el web3auth? ... si entra en login ... el web3auth si esta connected debe desconectarse, si no entraremos con el mismo owner -> misma HW

2023-09-28 10:20 UTC, merged